services:
  - type: web
    name: tesis-mvp
    env: python
    plan: free
    region: oregon
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.server:app --host 0.0.0.0 --port $PORT"
