services:
  - type: web
    name: TESIS-DETECCIONAR-SISTEMA
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.server:app --host 0.0.0.0 --port $PORT"
